name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Remote repo dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Remote Repo Dispatch
        run: |
          echo "Remote Repo Dispatch"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: brati-biswas-hyland
          repo: repository-dispatch-test
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: test.yml
          wait_interval: 10
          client_payload: '{}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true